Development
Aaron-RN/HTML-Building-With-Responsive-Design pull request #1
Opened 2019-09-16 15:03 UTC by Aaron-RN

Hey I'm unable to get in contact with my coding partner so I just decided to finish off the HTML curriculum alone since only 2 more collab projects were left...

2019-09-20 13:14 UTC, SunnyAsar requested changes
# Hey @Aaron-RN  👋 
### well done 👏  and project looks good But why are you working alone?
#### Things to note
- padding can be used as `padding: 15px 10px;` that will take care of horizontal and vertical instead of declaring all four vales as you did in the main.css
- Take out the comments in the mark-up and I must commend your use of html tags like `nav` and `footer` instead of generic `div`
- please remove the css you added for debugging  purposes i suppose
- finally, we have some liniting problems with git, please look through and fix them.

**Request another review when this is done**

2019-09-20 14:39 UTC, Aaron-RN commented
> # Hey @Aaron-RN 👋
> ### well done 👏 and project looks good But why are you working alone?
> #### Things to note
> * padding can be used as `padding: 15px 10px;` that will take care of horizontal and vertical instead of declaring all four vales as you did in the main.css
> * Take out the comments in the mark-up and I must commend your use of html tags like `nav` and `footer` instead of generic `div`
> * please remove the css you added for debugging  purposes i suppose
> * finally, we have some liniting problems with git, please look through and fix them.
> 
> **Request another review when this is done**

Can't get in contact with my coding partner...

2019-09-20 16:00 UTC, Aaron-RN commented
> * Take out the comments in the mark-up and I must commend your use of html tags like `nav` and `footer` instead of generic `div`

What do you consider the mark-up?

2019-09-21 03:01 UTC, bolah2009 approved these changes
# Nice job Team ... :clap: 

### The [clone](https://raw.githack.com/Aaron-RN/Building-With-Responsive-Design/82df751cb251b9f875b5f4d04067da4119c3a56f/index.html) looks good to me and responsive. :+1: 

For next (HTML/CSS) project, please follow `GitHub flow` [guidelines](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). What is missing here is a descriptive brance name instaed of `Development`.

#### [REQUIRED] Please I strongly recommend you do this before merging and taking note in next projects.
##### Make sure that repo looks professional
- Use meaningful commits messages. [Learn more here](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)
- Use meaningful names for  Pull Requests. See below.
- Add a short summary of changes in Pull Request description. See below.

#### :heavy_check_mark: This project is approved.
Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-09-21 03:01 UTC, bolah2009 commented on README.md
> +Github Link: https://github.com/Aaron-RN/Building-With-Responsive-Design
#### `OPTIONAL`

Can you add screenshots different breakpoint of the responsive [clone](https://raw.githack.com/Aaron-RN/Building-With-Responsive-Design/82df751cb251b9f875b5f4d04067da4119c3a56f/navbar.html). I think that would give this `README` a more descriptive and professional look. :blush:

2019-09-21 03:02 UTC, bolah2009 reviewed
# Rename PR

  ![rename PR](https://user-images.githubusercontent.com/36057474/63838245-ec569f80-c974-11e9-93a9-83a4db5c259f.gif)

-----

# Update PR description

  ![update-PR-description-html](https://user-images.githubusercontent.com/36057474/64305800-6e078800-cf88-11e9-82f0-04e13fd6cb8d.gif)

2019-09-22 17:08 UTC, merged